version: "3"

services:
    gitlab:
        image: "gitlab/gitlab-ce:latest"
        restart: "always"
        ports:
            - "8080:80"
            - "2222:22"
        volumes:
            - "./data/gitlab/config:/etc/gitlab"
            - "./data/gitlab/logs:/var/log/gitlab"
            - "./data/gitlab:/var/opt/gitlab"
    sonarqube:
        image: "sonarqube"
        ports:
            - "9000:9000"
        depends_on:
            - "db"
        environment:
            - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
        volumes:
            - "./data/sonarqube/conf:/opt/sonarqube/conf"
            - "./data/sonarqube/data:/opt/sonarqube/data"
            - "./data/sonarqube/extensions:/opt/sonarqube/extensions"
            - "./data/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins"
    db:
        image: "postgres"
        environment:
          - POSTGRES_USER=sonar
          - POSTGRES_PASSWORD=sonar
        volumes:
          - "./data/postgresql:/var/lib/postgresql"
          - "./data/postgresql/data:/var/lib/postgresql/data"
    jenkins:
        image: "jenkins:latest"
        ports:
            - "8000:8000"
        restart: "always"
        volumes:
            - "./data/jenkins:/var/jenkins_home"